config/routes.rb
Reportes::Application.routes.draw do
  get "reportes/index"
  get "reportes/show"
  get "reportes/edit"
  get "usuarios/index"
  get "usuarios/show"
  get "usuarios/edit"
  resources :sessions
  
   resources :users do
    resources :reportes
  end
  get "logout" => 'sessions#destroy', :as => 'logout' 
  get "login" => 'sessions#new', :as => 'login' 
  root to: 'sessions#new'
  match "signup", to: "users#new", via: [:get]
  match "profile", to: "sessions#profile", via: [:get]
  match "setting", to: "sessions#setting", via: [:get]
  namespace :admin do 
    resources :users do
      resources :reportes
    end
  end

end

app/models/reporte.rb
class Reporte < ActiveRecord::Base
	belongs_to :user
	validates :cedula, :presence => true 
	validates :nombre, :presence => true
	validates :telefono, :presence => true
	validates :asociado, :presence => true
	validates :resultado, :presence => true
	validates :referido, :presence => true
#	before_filter :find_user
	
#	def find_user
#		@user=User.find(params[:user_id])
#	end 

	def self.to_csv(options={})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |reporte|
				csv << reporte.attributes.values_at(*column_names)
			end
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reportes
	attr_accessor :password, :password_confirmation
	validates :usuario, :presence => true, :uniqueness => true, :length => {:in =>2..20}
	validates :password, :confirmation => true
	validates_length_of :password, :in => 6..20, :on => :create
	before_save :encrypt_password
	#after_save :clear_password
	EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	def self.authenticate(username_or_email="", login_password="")

    	if EMAIL_REGEX.match(username_or_email)
    	#if username_or_email
     	 user = User.find_by(email: username_or_email)
     	# 
    	else
      	  user = User.find_by(usuario: username_or_email)
      	  
      	  puts user
    	end
    	
    	if user && user.match_password(login_password)
      		return user
    	else
    	  return false
    	end
  	end

  	def match_password(login_password="")
  		
    	encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  	end

	def encrypt_password
		
		if password.present?
			self.salt=BCrypt::Engine.generate_salt
			self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
		end

	end	
  
	#def clear_password
		#self.password = nil
	#end


end

app/controllers/admin/reportes_controller.rb
class Admin::ReportesController < ApplicationController
  def index
  	@user=User.find(params[:user_id])
  	@reportes= @user.reportes.all
    @reportes= @user.reportes.order(:created_at)
    respond_to do |format|
      format.html
      format.csv { render text: @reportes.to_csv }
      format.xls #{ send_data @reportes.to_csv(col_sep: "\t") }
    end
  end

  def show
  	@user=User.find(params[:user_id])
  	@reportes=Reporte.find(params[:id])
  end

  def edit
  end

  def cvs

  end
end

app/controllers/admin/users_controller.rb
  class Admin::UsersController < ApplicationController
	#before_action :set_usuario, only: []
  before_filter :save_login_state, :only => [:new, :create]
  
  
  def new

  	@user = User.new

  end

  def create
    
  	@user=User.new(user_params)
    
  	if @user.save
  		flash[:notice]= "Ha creado el usuario correctamente"
  		#flash[:color]="valid"

  	else
  		flash[:notice]= "No se ha creado el usuario"
  		flash[:color]= "Verifique los parametros"
  	end
  	render "new"
    
  end	

  def index
    @user=User.all
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path

  end

  def edit
    @user=User.find(params[:id])

  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "EL usuario se ha actualizado"
    end
  end

  def show
    @user=User.find(params[:id])
    @reportes=@user.reportes.all
  end

  def set_usuario
  	@user=User.find(params[:id])
  end

	def user_params
	  params.require(:user).permit(:usuario, :password, :password_confirmation, :nombres, :apellido1, :apellido2)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
	def authenticate_user
		if session[:user_id]

		# set current user object to @current_user object variable
		@current_user = User.find session[:user_id]
		
		return true	
		else
			#redirect_to(:controller => 'sessions', :action => 'login')
			redirect_to(session_reporte_path)
			return false
		end
	end
	def save_login_state
		if session[:user_id]
			#redirect_to(:controller => 'sessions', :action => 'home')
			return false
		else
			return true
		end
	end
end

app/controllers/reportes_controller.rb
class ReportesController < ApplicationController
	before_action :set_reporte, only: [:show, :edit, :update, :destroy]	
		
	def new
		@user=User.find(params[:user_id])
		@reporte = @user.reportes.build
	end

	def create
		@user=User.find(params[:user_id])
		@reporte = @user.reportes.build(reporte_params)
		
		if @reporte.save 
		  render "show"
		else
		  render "new"
		end
	end

	def index
		@user=User.find(params[:user_id])
		@reportes = @user.reportes.all
	end

	def update
		if @reporte.update(reporte_params)
			redirect_to @reporte, notice: "El reporte se ha actualizado" 
		end
	end

	def edit
		#@reporte = Reporte.find(reporte_params[:id])

	end

	def destroy
		@user = User.find(params[:user_id])
		@reporte=@user.reportes.find(params[:id])
		@reporte.destroy
		redirect_to user_reportes_path

	end

	def show

	end	



	def reporte_params
		params.require(:reporte).permit(:cedula, :nombre, :apellido1, :apellido2, :dependencia, :telefono, :asociado, :resultado, :referido)
	end

	def set_reporte
		@user = User.find(params[:user_id])
		@reporte=Reporte.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :authenticate_user, :only => [:home, :profile, :setting]
	before_action :save_login_state, :only => [:new, :create]
	def new
	end



	def create
		
		authorized_user = User.authenticate(params[:username_or_email],params[:login_password])
		
		if authorized_user
			puts "se autorizo"
			session[:user_id] = authorized_user.id
			flash[:notice] = "Bienvenido, Has iniciado sesion como: #{authorized_user.usuario}"
			if authorized_user.usuario == "alagos"
				flash[:notice]= "Bienvenido administrador: #{authorized_user.usuario}"
				redirect_to(admin_users_path)
			else			
				redirect_to(user_reportes_path(session[:user_id]))
			end
			
			
		else
			puts "no se autorizo"
			flash[:notice] = "Usuario o contrasena invalidos"
			flash[:color]= "invalid"
			
			render :new	
		end

	end
	def destroy
		render "new"
	end

	def logout
		session[:user_id] = nil
		redirect_to :action => 'new'
	end

  	def home

  	end

  	def profile
  	end

  	def setting
  	end
end
	

app/helpers/admin/reportes_helper.rb
module Admin::ReportesHelper
end

app/helpers/admin/usuarios_helper.rb
module Admin::UsuariosHelper
end

app/helpers/administrador_helper.rb
module AdministradorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/reportes/edit.html.erb
<h1>Admin::Reportes#edit</h1>
<p>Find me in app/views/admin/reportes/edit.html.erb</p>

app/views/admin/reportes/index.html.erb
<br>
<div>
    <h2>Administracion de Reportes</h2>
</div>
<div>
    <%= link_to '<button type="button", class="btn btn-success">Regresar a Usuarios</button>'.html_safe, admin_users_path %>

    <%= link_to '<button type="button", class="btn btn-primary", Id="lista_reportes">Enviar a CSV</button>'.html_safe, admin_user_reportes_path(format: "csv") %>

    <%= link_to '<button type="button", class="btn btn-danger", Id="lista_reportes">Enviar a Excel</button>'.html_safe, admin_user_reportes_path(format: "xls") %>

    <table class="table table-bordered table-striped">
     <thead>
            <tr>
                <th>Cedula</th>
                <th>Nombres</th>
                <th>Apellido1</th>
                <th>Apellido2</th>
                <th>Creado</th>
                <th>Actualizado</th>
           </tr>
        </thead>
        <%@reportes.each do |reporte|%>
            <tbody>
                <tr>
                    <td><%=reporte.cedula%> </td>
                    <td><%=reporte.nombre%> </td>
                   <td><%=reporte.apellido1%> </td>
                    <td><%=reporte.apellido2%> </td>
                    <td><%=reporte.created_at%></td>
                    <td><%=reporte.updated_at%></td>
                    <td><%=link_to 'Ver Reporte', admin_user_reporte_path(@user,reporte)%> </td>
                 </tr>


           </tbody>
        <%end%>
       
    </table>
</div>
<div>
    
</div>

app/views/admin/reportes/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">CEDULA</Data></Cell>
        <Cell><Data ss:Type="String">NOMBRES</Data></Cell>
        <Cell><Data ss:Type="String">APELLIDO1</Data></Cell>
        <Cell><Data ss:Type="String">APELLIDO2</Data></Cell>
        <Cell><Data ss:Type="String">AREA DE TRABAJO</Data></Cell>
        <Cell><Data ss:Type="String">TELEFONO</Data></Cell>
        <Cell><Data ss:Type="String">ASOCIADO</Data></Cell>
        <Cell><Data ss:Type="String">RESULTADO</Data></Cell>
        <Cell><Data ss:Type="String">REFERIDOS</Data></Cell>
        <Cell><Data ss:Type="String">FECHA CREACION</Data></Cell>
        <Cell><Data ss:Type="String">FECHA ULTIMA ACTUALIZACION</Data></Cell>
      </Row>
    <% @reportes.each do |reporte| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= reporte.id %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= reporte.cedula %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reporte.nombre %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reporte.apellido1 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reporte.apellido2 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reporte.dependencia %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= reporte.telefono %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reporte.asociado %></Data></Cell>
        <Cell><Data ss:Type="String"><%= reporte.resultado %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= reporte.referido %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= reporte.created_at %></Data></Cell>
        <Cell><Data ss:Type="Date"><%= reporte.updated_at  %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/reportes/show.html.erb
<table class="table table-bordered">

    <thead>
    </thead>
 	<tbody>
    	<tr>
        	<td>Nombres: <%=@reportes.nombre%></td>
        </tr>
        <tr>        	
        	<td>Apellido: <%=@reportes.apellido1%></td>
        </tr>   
        <tr>
        	<td>Edad: <%=@reportes.apellido2%></td>
        </tr> 
        <tr>
        	<td>Telefono: <%=@reportes.dependencia%></td>
        </tr>
        <tr>
        	<td>Asociado: <%=@reportes.asociado%></td>
        </tr>
        <tr>
        	<td>Resultado: <%=@reportes.resultado%></td>
        </tr>
        <tr>
        	<td>Referidos: <%=@reportes.referido%></td>
        </tr>
        <tr>
        	<td>
        		<%= link_to '<button type="button", class="btn btn-info">Volver a reportes</button>'.html_safe, admin_user_reportes_path %>
				
				<%#link_to '<button type="button">Whatch properties</button>'.html_safe, persona_propiedades_path(@persona) %>      
         	
         	</td>
        </tr>
        
    </tbody>
    

</table>

app/views/admin/users/_form.html.erb
<div class= "sign_form">
	
	<%if @user.errors.any?%>
		<ul class= "Signup_Errors">
			<%for message_error in @user.errors.full_messages%>
				<li>* <%=message_error%></li>
			<%end%>
		</ul>
	<%end%>

	<%= form_for([:admin, @user]) do |f|%>
		<p> Usuario: </br><%=f.text_field :usuario%></p>
		<p> Contrasena: </br><%=f.password_field :password%></p>
		<p> Confirmar contrasena: </br> <%=f.password_field :password_confirmation%></p>
		<p> Nombres: </br><%=f.text_field :nombres%></p>
		<p> Apellido1: </br><%=f.text_field :apellido1%></p>
		<p> Apellido2: </br><%=f.text_field :apellido2%></p>

		<%=f.submit "Salvar Usuario"%>
		
		<%= link_to '<button type="button" class="btn btn-primary">Regresar</button>'.html_safe, admin_users_path %>
	<%end%>

</div>

app/views/admin/users/edit.html.erb
<%=render "form"%>

app/views/admin/users/index.html.erb
<div align="right">
    <%=link_to "Cerrar Sesion", logout_path%>
</div>
<div align="left">
    <h2>Administracion de Usuarios</h2>
</div>
<table class="table">

    <thead>
        <tr>
            <th class="info"> ID </th>
            <th class="info"> USUARIO </th>
            <th class="info"> NOMBRES </th>
            <th class="info"> PRIMER APELLIDO </th>
            <th class="info"> SEGUNDO APELLIDO </th>
        </tr>
    </thead>
    <tbody> 
    
        <%@user.each do |usuario|%>
            <tr class="warning">

                <td><%=usuario.id%></td>
                <td><%=usuario.usuario%></td>   
        
                <td><%=usuario.nombres%></td>
        
                <td><%=usuario.apellido1%></td>
        
                <td><%=usuario.apellido2%></td>

                <td><%= link_to "Editar", edit_admin_user_path(usuario) %></td>
                <td><%= link_to "Eliminar", admin_user_path(usuario), :confirm => "Esta seguro de eliminar este usuario", :method => :delete  %></td>
                <td><%= link_to "Ver", admin_user_reportes_path(usuario)%></td>

            </tr>

        <%end%>
        <%= link_to '<button type="button" class="btn btn-primary">Ingresar Usuario Nuevo</button>'.html_safe, new_admin_user_path %>

    </tbody>

</table>


    
    
    
    
    

app/views/admin/users/new.html.erb
<h1>Crear usuarios</h1>
<%=render "form"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reportes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

	<% flash.each do |name, message|%>
		<%= content_tag :div, message, :id => "flash_#{name}"%>
	<%end%>
	<%= yield %>
</div>
</body>
</html>

app/views/reportes/_form.html.erb
<div class="well">

	
	<%=form_for ([@user ,@reporte]) do |f|%>

		<table class="table">
			
			<tbody>
				<div class="form-group">
					<tr>
						<th width="5px">
							<%=f.label :cedula%> 
							
						</th>
						<th>
							<%=f.text_field :cedula%>
						</th>

					</tr>
				</div>
					<div class="form-group">
						<tr>
							<th>
								<%=f.label :nombre, "Nombres"%>
							</th>
							<th>
								<%=f.text_field :nombre%>
							</th>

						</tr>
					</div>
					<div class="form-group">
						<tr>
							<th>
								<%=f.label :apellido1%>
							</th>
							<th>
								<%=f.text_field :apellido1%>
							</th>

						</tr>
					</div>
					<div class="form-group">
						<tr>
							<th>
								<%=f.label :apellido2%>
							</th>
							<th>
								<%=f.text_field :apellido2%>
							</th>

						</tr>
					</div>
					<div class="form-group">
						<tr>
							<th>
								<%=f.label :dependencia, "Cargo Laboral"%>
							</th>
							<th>
								<%=f.text_field :dependencia%>
							</th>

						</tr>
					</div>

					<div class="form-group">
						<tr>
							<th>
								<%=f.label :telefono%>
							</th>
							<th>
								<%=f.text_field :telefono%>
							</th>

						</tr>
					</div>
					<div class="form-group">
						<tr>
							<th>
								<%=f.label :asociado%>
							</th>
							<th>
								<%=f.text_field :asociado%>
							</th>

						</tr>
					</div>

					<div class="form-group">
						<tr>
							<th>
								<%=f.label :resultado%>
							</th>
							<th>
								<%=f.text_area :resultado%>
							</th>

						</tr>
					</div>
					<div class="form-group">
						<tr>
							<th>
								<%=f.label :referido, "Cuantos Referidos"%>	
							</th>
							<th>
								<%=f.text_field :referido%>
							</th>

						</tr>
					</div>
						
				<tr>
					<td>
						<%=f.submit%>
					</td>
				</tr>	
			</tbody>		
		</table>

	<%end%>

</div>

app/views/reportes/edit.html.erb
<%=render "form"%>

app/views/reportes/index.html.erb
<div align="right">
    <%=link_to "Cerrar Sesion", logout_path%>
</div>
<br>
<br>
<br>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Cedula</th>
            <th>Nombres</th>
            <th>Apellido1</th>
            <th>Apellido2</th>
        </tr>
    </thead>
    <%@reportes.each do |reporte|%>
        <tbody>
            <tr>
                <td><%=reporte.cedula%> </td>
                <td> <%=reporte.nombre%> </td>
                <td> <%=reporte.apellido1%> </td>
                <td> <%=reporte.apellido2%> </td>
                <td><%=link_to "Ver Registro", user_reporte_path(@user, reporte)%></td>
                <td><%=link_to "Editar Registro", edit_user_reporte_path(@user ,reporte)%></td>
                <td><%=link_to "Borrar Registro", user_reporte_path(@user, reporte), :confirm => "Estas seguro de borrar este registro", :method => :delete%></td>
                </tr>
        </tbody>
    <%end%>
</table>
<%= link_to "Ingresar Registro", new_user_reporte_path%>

app/views/reportes/new.html.erb
<div class="row-fluid">
	<h1>Ingrese los datos de la Asesoria</h1>
	<%=render "form"%>
</div>

app/views/reportes/show.html.erb
<table class="table table-bordered">

    <thead>
    </thead>
 	<tbody>
    	<tr>
        	<td>Nombres: <%=@reporte.nombre%></td>
        </tr>
        <tr>        	
        	<td>Apellido: <%=@reporte.apellido1%></td>
        </tr>   
        <tr>
        	<td>Edad: <%=@reporte.apellido2%></td>
        </tr> 
        <tr>
        	<td>Telefono: <%=@reporte.dependencia%></td>
        </tr>
        <tr>
        	<td>Asociado: <%=@reporte.asociado%></td>
        </tr>
        <tr>
        	<td>Resultado: <%=@reporte.resultado%></td>
        </tr>
        <tr>
        	<td>Referidos: <%=@reporte.referido%></td>
        </tr>
        <tr>
        	<td>
        		<%= link_to '<button type="button">Back to Ingresar</button>'.html_safe, user_reportes_path %>
				
				<%#link_to '<button type="button">Whatch properties</button>'.html_safe, persona_propiedades_path(@persona) %>      
         	
         	</td>
        </tr>
        
    </tbody>
    

</table>

app/views/users/index.html.erb
<table class="table table-striped">
    <thead>
        <tr>
            <th>                    
            	Usuario
            </th>
            <th>Id</th>
            <th>
            	Nombres
            </th>
            <th> </th>
            <th>Apellido1 </th>
            <th>Apellido2 </th>
        </tr>
    </thead>
    <%@user.each do |usuario|%>
    
    <tbody>
    	
         <tr>
	            <td><%=usuario.usuario %></td>
    	        <td><%=usuario.nombres %></td>
                <td><%=usuario.apellido1 %></td>
                <td><%=usuario.apellido2 %></td>
        	</tr>
    	   
        <%end%>
    </tbody>
</table>
<%= link_to '<button type="button" class="btn btn-primary">Regresar</button>'.html_safe, administrador_index_path %>

app/views/users/new.html.erb
<div class= "sign_form">
	
	<%if @user.errors.any?%>
		<ul class= "Signup_Errors">
			<%for message_error in @user.errors.full_messages%>
				<li>* <%=message_error%></li>
			<%end%>
		</ul>
	<%end%>
	<h1>Crear usuarios</h1>
	<%= form_for(:user, :url => {:controller =>'users', :action => 'create'}) do |f|%>
		<p> Usuario: </br><%=f.text_field :usuario%></p>
		<p> Contrasena: </br><%=f.password_field :password%></p>
		<p> Confirmar contrasena: </br> <%=f.password_field :password_confirmation%></p>
		<p> Nombres: </br><%=f.text_field :nombres%></p>
		<p> Apellido1: </br><%=f.text_field :apellido1%></p>
		<p> Apellido2: </br><%=f.text_field :apellido2%></p>

		<%=f.submit :Crear%>
		
		<%= link_to '<button type="button" class="btn btn-primary">Regresar</button>'.html_safe, administrador_index_path %>
	<%end%>

</div>